spring:
  application:
    name:
      SpaceCommunityBackendJWTOAuth
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  jwt:
    access:
      expiration:
        900000
    refresh:
      expiration:
        20160000
    secret:
      bla
  datasource:
    driver-class-name:
      com.mysql.cj.jdbc.Driver
    url:
      jdbc:mysql://localhost:3306/SpaceBackendDB
    username:
      root
    password:
      ohi
  data:
    redis:
      host:
        localhost
      port:
        6379
  cloud:
    aws:
      stack:
        auto:
          false
      credentials:
        access-key:
          ac
        secret-key:
          sc
      s3:
        bukkit:
          spacecommunityimage
      region:
        static:
          us-west-1