spring:
  application:
    name:
      SpaceCommunityBackendJWTOAuth
  jpa:
    properties:
      hibernate:
        show_sql:
          true
        ddl-auto:
          update
  jwt:
    access:
      expiration:
        0
    refresh:
      expiration:
        0
    secret:
      afsdjn
  datasource:
    driver-class-name:
      aldm
    url:
      dkmad
    username:
      niga
    password:
      mm
  data:
    redis:
      host:
        halo
      port:
        1111

debug:
  true
